### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by annezao** [horsicq/XTranslation#109]
It seems that the translation into PT-BR is correct but the README says it is less than 50%, is that correct?

**Comment by horsicq** [comment]
It is a bug. I will fix it! Thank you for the report!

**Comment by greenozon** [comment]
@horsicq   is it kind of manual work?

**Comment by horsicq** [comment]
Oh. I should remove the counter. It is so broken. :(

**Comment by jimdi** [comment]
at now it's fixed
