### ISSUE TITLE
App crashes when clicked on Colors

### ISSUE THREAD

**Issue by blue-devil** [horsicq/XTranslation#111]
Version : DiE **v3.0.8**

When you click `Options > Disasm > Colors` app crashes.

It does not crash on version **v3.0.7**

**Comment by horsicq** [comment]
Thanks!

**Comment by greenozon** [comment]
Works well in brand new 3.0.9 version
@blue-devil   how about you!

**Comment by horsicq** [comment]
Thanks for the testing! :)

**Comment by blue-devil** [comment]
Hello
Tested on:

* macOS (intel and arm)
* Linux (intel and arm [manually compiled])
* Windows (intel and arm)

all OK
we can close the issue

#Close #111

**Comment by horsicq** [comment]
Thanks! :)
