### ISSUE TITLE
Hi! is Swedish a Language that would also fit?

### ISSUE THREAD

**Issue by loneicewolf** [horsicq/XTranslation#134]
# Hello there!

## First things first
I really appreciate the DiE tool; it's Invaluable. 
It's a marvelous tool! 

**Thank you**!

## Question
I am asking if Swedish is a language that would also fit in the translation? As I am Swedish, and the tool has been helpful to me, I wanted to "give back" the "help", in form of translation, if it fits. Which is why I ask! :)

## Wishes!
Wishes from Sweden!

*Will.*

**Comment by greenozon** [comment]
welcome!
get english translation, make a copy, translate to Swedish and commit back
good luck :)

**Comment by loneicewolf** [comment]
Ah okay! thank you;

**Comment by loneicewolf** [comment]
@jimdi  of cours! sv (Swedish) like, äÄ  åÅ  öÖ

**Comment by loneicewolf** [comment]
## One question!  - possible duplicates in `en` dict? 
(and maybe in more?)

is duplicates meant to be there? there is 2
- msgid "data"
- msgid "data"

**Comment by jimdi** [comment]
just compare with any translation, most easy way. 

we'll check before accept merge request, mkay?

**Comment by loneicewolf** [comment]
I am native speaker (I am Swedish myself)

and yes, please do check! I will double check before merging to be sure,

have a great night!

**Comment by loneicewolf** [comment]
# Update:  99% done

- [x] I am 100% done with the typing, 
- [ ] 99% done overall
  - 1% = proofreading before making the PR
  - Not only to see so **"grammatically correct"** but **"contextually correctly too"**

As *Swedish as a language can sometimes be weird or unique* - which is why I spend extra time thinking of the possible scenarios, one word that is "translated" might work perfectly in some sense, but will make it very wrong in another like-scenario(I.e, some times it swaps places, so I have tried to be consistent))

**Comment by greenozon** [comment]
@loneicewolf   amazing stuff!
super speed

are you also the user of the tool?

**Comment by loneicewolf** [comment]
## Hi!
Thanks! I tried my best, ill make a PR now, hope it all goes well, please point out anything or any questions (if any) It was a pleasure! I always wanted to show my appreciation to this tool & it's communities, because it's been invaluable. Such a great tool, DiE (and more).

@greenozon 
> The tool
?

You mean DiE? Yes, I love it, along with Radare2 and sometimes Ghidra;

in case of any translation tool? I used my own language experience, even if I actually prefer English, this was a nice exercise actually! I don't use Swedish so often, so ^_^

**Comment by loneicewolf** [comment]
# PR made! 
Thanks for all the help! ❤️  as usual, __point out if anything is off__, I have the day off to take care of any and every things that might come up. 

Saluting from Sweden!
- PR : https://github.com/horsicq/XTranslation/issues/134

**Comment by horsicq** [comment]
Thanks!
