### ISSUE TITLE
Question Regarding File Sorting

### ISSUE THREAD

**Issue by loneicewolf** [horsicq/XTranslation#136]
# Question Regarding File Sorting
### Hello!

It's been a pleasure to add Swedish to this repo, if it needs any fixing, just ping me in any issue & I will do my best to take a look at it.

I have a **Question related to file organization.** 
# Question
### Does the order of the contents in the files matter?

- For example, can I sort the Swedish files contextually?
I was thinking of grouping related entries together, such as
- keeping any context-related items grouped (`true:sant,false:falskt`)
- `Data:Data` and `data:data` closer to each other instead of being separated by a few hundred lines.

### What this will do if order is not important
- It will make it easier to manually go trough things, so the translator does not have to search for "data" and hit next, translate, next, translate

## If order is important
**Then please close this issue! I completely understand and I thought it might be!**

❤️  Thank you once more for these tools. I will see if I can contribute some more to other languages, to make them 100% as well.

## Final Words
Thanks once more!

Will
Sincere wishes from Sweden

**Comment by horsicq** [comment]
Sure! You could sort it. If you really need. :)

**Comment by loneicewolf** [comment]
Oh okay! thank you, have a great week!
